### ISSUE TITLE
18th Feb Project Discussion - Getting Started 

### ISSUE THREAD

**Issue by urvi09** [suryanshsharma/Votester#9]
![imag0003](https://cloud.githubusercontent.com/assets/11045874/13148763/aa8641dc-d684-11e5-8f3f-493ec3ec91f4.jpg)
![imag0004](https://cloud.githubusercontent.com/assets/11045874/13148766/ad8100de-d684-11e5-8246-22799207c078.jpg)
![imag0005](https://cloud.githubusercontent.com/assets/11045874/13148768/af37c9d0-d684-11e5-82cf-2d9547eb8e8d.jpg)

**Comment by suryanshsharma** [comment]
Commit it to your branch and push
